class AddColumnsffToFeatureds < ActiveRecord::Migration[5.2]
  def change
    add_column :featureds, :user_id, :integer
    add_column :featureds, :ff_title, :string
    add_column :featureds, :ff_link, :string
    add_column :featureds, :ff_source, :string
    add_column :featureds, :ff_hashtag, :string
    add_column :featureds, :ff_description, :text
    add_column :featureds, :ff_is_price, :float
    add_column :featureds, :ff_was_price, :float
    add_column :featureds, :ff_pct, :float
    add_column :featureds, :ff_spare_01, :string
    add_column :featureds, :ff_spare_02, :string
    add_column :featureds, :ff_spare_03, :string
    add_column :featureds, :ff_spare_04, :string
    add_column :featureds, :ff_spare_05, :string
    add_column :featureds, :ff_spare_06, :string
    add_column :featureds, :ff_spare_07, :string
    add_column :featureds, :ff_spare_08, :string
    add_column :featureds, :ff_spare_09, :string
    add_column :featureds, :ff_spare_10, :string
    add_column :featureds, :ff_spare_11, :string
    add_column :featureds, :ff_spare_12, :string
    add_column :featureds, :ff_spare_13, :string
    add_column :featureds, :ff_spare_14, :string
    add_column :featureds, :ff_spare_15, :string
    add_column :featureds, :ff_spare_16, :string
    add_column :featureds, :ff_spare_17, :string
    add_column :featureds, :ff_spare_18, :string
    add_column :featureds, :ff_spare_19, :string
    add_column :featureds, :ff_spare_20, :string
    add_column :featureds, :ff_spare_21, :string
    add_column :featureds, :ff_spare_22, :string
    add_column :featureds, :ff_spare_23, :string
    add_column :featureds, :ff_spare_24, :string
    add_column :featureds, :ff_spare_25, :string
    add_column :featureds, :ff_spare_26, :string
    add_column :featureds, :ff_spare_27, :string
    add_column :featureds, :ff_spare_28, :string
    add_column :featureds, :ff_spare_29, :string
    add_column :featureds, :ff_spare_30, :string
    add_column :featureds, :ff_spare_31, :text
    add_column :featureds, :ff_spare_32, :text
    add_column :featureds, :ff_spare_33, :text
    add_column :featureds, :ff_spare_34, :text
    add_column :featureds, :ff_spare_35, :text
    add_column :featureds, :ff_spare_36, :text
    add_column :featureds, :ff_spare_37, :text
    add_column :featureds, :ff_spare_38, :text
    add_column :featureds, :ff_spare_39, :text
    add_column :featureds, :ff_spare_40, :text
    add_column :featureds, :ff_spare_41, :float
    add_column :featureds, :ff_spare_42, :float
    add_column :featureds, :ff_spare_43, :float
    add_column :featureds, :ff_spare_44, :float
    add_column :featureds, :ff_spare_45, :float
    add_column :featureds, :ff_spare_46, :float
    add_column :featureds, :ff_spare_47, :float
    add_column :featureds, :ff_spare_48, :float
    add_column :featureds, :ff_spare_49, :float
    add_column :featureds, :ff_spare_50, :float
    add_column :featureds, :ff_spare_51, :float
    add_column :featureds, :ff_spare_52, :float
    add_column :featureds, :ff_spare_53, :float
    add_column :featureds, :ff_spare_54, :float
    add_column :featureds, :ff_spare_55, :float
    add_column :featureds, :ff_spare_56, :integer
    add_column :featureds, :ff_spare_57, :integer
    add_column :featureds, :ff_spare_58, :integer
    add_column :featureds, :ff_spare_59, :integer
    add_column :featureds, :ff_spare_60, :integer
    add_column :featureds, :ff_spare_61, :decimal
    add_column :featureds, :ff_spare_62, :decimal
    add_column :featureds, :ff_spare_63, :decimal
    add_column :featureds, :ff_spare_64, :decimal
    add_column :featureds, :ff_spare_65, :decimal
    add_column :featureds, :ff_spare_66, :datetime
    add_column :featureds, :ff_spare_67, :datetime
    add_column :featureds, :ff_spare_68, :datetime
    add_column :featureds, :ff_spare_69, :datetime
    add_column :featureds, :ff_spare_70, :datetime
    add_column :featureds, :ff_spare_71, :date
    add_column :featureds, :ff_spare_72, :date
    add_column :featureds, :ff_spare_73, :date
    add_column :featureds, :ff_spare_74, :date
  end
end
