class AddColguideToGuides < ActiveRecord::Migration[5.2]
  def change
    add_column :guides, :gui_title, :string
    add_column :guides, :gui_link, :string
    add_column :guides, :gui_source, :string
    add_column :guides, :gui_hashtag, :string
    add_column :guides, :gui_description, :text
    add_column :guides, :gui_is_price, :float
    add_column :guides, :gui_was_price, :float
    add_column :guides, :gui_pct, :float
    add_column :guides, :gui_spare_01, :string
    add_column :guides, :gui_spare_02, :string
    add_column :guides, :gui_spare_03, :string
    add_column :guides, :gui_spare_04, :string
    add_column :guides, :gui_spare_05, :string
    add_column :guides, :gui_spare_06, :string
    add_column :guides, :gui_spare_07, :string
    add_column :guides, :gui_spare_08, :string
    add_column :guides, :gui_spare_09, :string
    add_column :guides, :gui_spare_10, :string
    add_column :guides, :gui_spare_11, :string
    add_column :guides, :gui_spare_12, :string
    add_column :guides, :gui_spare_13, :string
    add_column :guides, :gui_spare_14, :string
    add_column :guides, :gui_spare_15, :string
    add_column :guides, :gui_spare_31, :text
    add_column :guides, :gui_spare_32, :text
    add_column :guides, :gui_spare_33, :text
    add_column :guides, :gui_spare_34, :text
    add_column :guides, :gui_spare_35, :text
    add_column :guides, :gui_spare_36, :text
    add_column :guides, :gui_spare_37, :text
    add_column :guides, :gui_spare_38, :text
    add_column :guides, :gui_spare_39, :text
    add_column :guides, :gui_spare_40, :text
    add_column :guides, :gui_spare_41, :float
    add_column :guides, :gui_spare_42, :float
    add_column :guides, :gui_spare_43, :float
    add_column :guides, :gui_spare_44, :float
    add_column :guides, :gui_spare_45, :float
    add_column :guides, :gui_spare_46, :float
    add_column :guides, :gui_spare_47, :float
    add_column :guides, :gui_spare_48, :float
    add_column :guides, :gui_spare_49, :float
    add_column :guides, :gui_spare_50, :float
    add_column :guides, :gui_spare_51, :float
    add_column :guides, :gui_spare_52, :float
    add_column :guides, :gui_spare_53, :float
    add_column :guides, :gui_spare_54, :float
    add_column :guides, :gui_spare_55, :float
    add_column :guides, :gui_spare_56, :integer
    add_column :guides, :gui_spare_57, :integer
    add_column :guides, :gui_spare_58, :integer
    add_column :guides, :gui_spare_59, :integer
    add_column :guides, :gui_spare_60, :integer
    add_column :guides, :gui_spare_61, :decimal
    add_column :guides, :gui_spare_62, :decimal
    add_column :guides, :gui_spare_63, :decimal
    add_column :guides, :gui_spare_64, :decimal
    add_column :guides, :gui_spare_65, :decimal
    add_column :guides, :gui_spare_66, :datetime
    add_column :guides, :gui_spare_67, :datetime
    add_column :guides, :gui_spare_68, :datetime
    add_column :guides, :gui_spare_69, :datetime
    add_column :guides, :gui_spare_70, :datetime
    add_column :guides, :gui_spare_71, :date
    add_column :guides, :gui_spare_72, :date
    add_column :guides, :gui_spare_73, :date
    add_column :guides, :gui_spare_74, :date
    add_column :guides, :gui_spare_75, :date
  end
end
